### ISSUE TITLE
貌似logout并没有真的logout

### ISSUE THREAD

**Issue by okjesse** [haodi/zia#1]
点了logout后，然后再点login会自动登陆进去，不需要输入用户名，密码

**Comment by haodi** [comment]
打开F12，看一下logout后再点击login后的跳转流程，access_token并没有过期。

**Comment by haodi** [comment]
@okjesse 打开F12，看一下logout后再点击login后的跳转流程，access_token并没有过期。

**Comment by okjesse** [comment]
@haodi  感谢您的回复，这个问题我也发现了，而且在前台我把session删掉，刷新下也还会自动登陆。我有两个问题，第一个是我在session删除的情况下，后台是如何知道这个请求对应的access_token的呢。第二个就是怎么样可以在logout的时候去处理access_token做到真正的完全退出呢。

**Comment by okjesse** [comment]
已经解决了，谢谢啦
